import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F5F5F5", padding: 20, justifyContent: "center", },
    header: { fontSize: 22, fontWeight: "bold", marginBottom: 10, textAlign: "center", },
    card: {
        backgroundColor: "#FFF",
        padding: 15,
        marginVertical: 10,
        borderRadius: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    title: { fontSize: 18, fontWeight: "bold" },
    description: { fontSize: 14, color: "#555", marginVertical: 5 },
    date: { fontSize: 12, color: "#888" },
    status: { fontSize: 14, fontWeight: "bold", marginTop: 5 },
    label: {
        fontSize: 16,
        fontWeight: "500",
        marginBottom: 5,
    },
    input: {
        height: 40,
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        paddingHorizontal: 10,
        backgroundColor: "#fff",
        marginBottom: 15,
    },
    searchResult: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#ddd",
        backgroundColor: "#eaeaea",
    },
    userItem: {
        fontSize: 14,
        padding: 5,
        backgroundColor: "#e6f7ff",
        marginBottom: 5,
        borderRadius: 5,
    },
    fab: {
        position: "absolute",
        right: 20,
        bottom: 20,
        backgroundColor: "#007bff",
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 2 },
        elevation: 5,
    },
    inputContainer: {
        position: "relative",
    },
    dropdown: {
        position: "absolute",
        top: 50,
        left: 0,
        right: 0,
        backgroundColor: "#fff",
        borderRadius: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
        zIndex: 1000,
    },
    dropdownItem: {
        flexDirection: "row",
        alignItems: "center",
        padding: 12,
        borderBottomWidth: 1,
        borderBottomColor: "#F0EDFF",
    },
    dropdownItemText: {
        fontSize: 16,
        color: "#333",
    },
    noResultText: {
        padding: 12,
        fontSize: 16,
        color: "#888",
        textAlign: "center",
    },
    userEmail: {
        fontSize: 14,
        color: "#666",
    },
    removeUser: {
        fontSize: 18,
        color: "red",
        fontWeight: "bold",
        marginLeft: 10,
    },
    dateInput: {
        height: 40,
        justifyContent: "center",
        alignItems: "center",
        borderColor: "#ccc",
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginBottom: 15,
        textAlign: "center",
        backgroundColor: "#f9f9f9",
        color: "#333",
    },
    createButton: {
        backgroundColor: "#6B4CE6",
        padding: 15,
        borderRadius: 8,
        alignItems: "center",
        marginTop: 20,
        shadowColor: "#6B4CE6",
        shadowOffset: {
            width: 0,
            height: 4,
        },
        shadowOpacity: 0.2,
        shadowRadius: 5,
        elevation: 3,
    },
    createButtonText: {
        color: "#FFFFFF",
        fontSize: 16,
        fontWeight: "600",
    },
    formSection: {
        backgroundColor: '#FFFFFF',
        borderRadius: 10,
        padding: 15,
        marginBottom: 15,
        shadowColor: "#6B4CE6",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    scrollContainer: {
        flexGrow: 1,
        padding: 20,
    },
    memberCard: {
        flexDirection: 'row',
        alignItems: 'center',
        backgroundColor: '#FFFFFF',
        padding: 12,
        marginBottom: 8,
        borderRadius: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 1,
        },
        shadowOpacity: 0.1,
        shadowRadius: 2,
        elevation: 2,
    },
    memberInfo: {
        flex: 1,
        flexDirection: 'row',
        alignItems: 'center',
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 12,
    },
    userName: {
        fontSize: 16,
        fontWeight: "500",
        color: "#333",
        flex: 1,
    },
    removeButton: {
        padding: 8,
        marginLeft: 'auto',
    },
    removeText: {
        fontSize: 18,
        color: "#FF4444",
    },
    membersList: {
        marginTop: 10,
    },
    modalOverlay: {
        flex: 1,
        backgroundColor: 'rgba(0, 0, 0, 0.5)',
        justifyContent: 'center',
        alignItems: 'center',
        padding: 20,
    },
    modalContent: {
        backgroundColor: 'white',
        borderRadius: 10,
        width: '100%',
        maxHeight: '70%',
        padding: 15,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
        elevation: 5,
    },
    searchContainer: {
        flexDirection: 'row',
        alignItems: 'center',
        marginBottom: 10,
    },
    searchInput: {
        flex: 1,
        height: 40,
        borderWidth: 1,
        borderColor: '#E0DCFF',
        borderRadius: 8,
        paddingHorizontal: 10,
        marginRight: 10,
    },
    closeButton: {
        padding: 5,
    },
    closeButtonText: {
        fontSize: 24,
        color: '#666',
    },
    addMemberButton: {
        backgroundColor: '#F0EDFF',
        padding: 12,
        borderRadius: 8,
        marginBottom: 15,
        borderWidth: 1,
        borderColor: '#E0DCFF',
    },
    addMemberButtonText: {
        color: '#6B4CE6',
        textAlign: 'center',
        fontSize: 16,
        fontWeight: '500',
    },
    toastContainer: {
        paddingHorizontal: 15,
        paddingVertical: 10,
        backgroundColor: '#fff',
        borderRadius: 8,
        shadowColor: "#000",
        shadowOffset: {
            width: 0,
            height: 2,
        },
        shadowOpacity: 0.25,
        shadowRadius: 3.84,
    },
    
});
