import { StyleSheet } from "react-native";

export const styles = StyleSheet.create({
    container: { flex: 1, backgroundColor: "#F5F5F5", padding: 20, justifyContent: "center", },
    header: { fontSize: 22, fontWeight: "bold", marginBottom: 10, textAlign: "center", },
    card: {
        backgroundColor: "#FFF",
        padding: 15,
        marginVertical: 10,
        borderRadius: 10,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "space-between",
        shadowColor: "#000",
        shadowOpacity: 0.1,
        shadowRadius: 4,
        elevation: 2,
    },
    title: { fontSize: 18, fontWeight: "bold" },
    description: { fontSize: 14, color: "#555", marginVertical: 5 },
    date: { fontSize: 12, color: "#888" },
    status: { fontSize: 14, fontWeight: "bold", marginTop: 5 },
    label: {
        fontSize: 16,
        fontWeight: "500",
        marginBottom: 5,
    },
    input: {
        height: 40,
        borderWidth: 1,
        borderColor: "#ccc",
        borderRadius: 8,
        paddingHorizontal: 10,
        backgroundColor: "#fff",
        marginBottom: 15,
    },
    searchResult: {
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#ddd",
        backgroundColor: "#eaeaea",
    },
    userItem: {
        fontSize: 14,
        padding: 5,
        backgroundColor: "#e6f7ff",
        marginBottom: 5,
        borderRadius: 5,
    },
    fab: {
        position: "absolute",
        right: 20,
        bottom: 20,
        backgroundColor: "#007bff",
        width: 60,
        height: 60,
        borderRadius: 30,
        justifyContent: "center",
        alignItems: "center",
        shadowColor: "#000",
        shadowOpacity: 0.3,
        shadowOffset: { width: 0, height: 2 },
        elevation: 5,
    },
    inputContainer: {
        position: "relative",
    },
    dropdown: {
        position: "absolute",
        top: 55, // Hiển thị ngay dưới input
        left: 0,
        right: 0,
        backgroundColor: "#fff",
        borderRadius: 10,
        shadowColor: "#000",
        shadowOffset: { width: 0, height: 4 },
        shadowOpacity: 0.2,
        shadowRadius: 6,
        elevation: 6, // Hiệu ứng bóng trên Android
        zIndex: 1000,
        maxHeight: 150,
        overflow: "hidden",
    },
    dropdownItem: {
        flexDirection: "row",
        alignItems: "center",
        padding: 10,
        borderBottomWidth: 1,
        borderBottomColor: "#eee",
    },
    dropdownItemText: {
        fontSize: 16,
        color: "#333",
    },
    noResultText: {
        padding: 12,
        fontSize: 16,
        color: "#888",
        textAlign: "center",
    },
    avatar: {
        width: 40,
        height: 40,
        borderRadius: 20,
        marginRight: 10,
    },
    userName: {
        fontSize: 16,
        fontWeight: "bold",
    },
    userEmail: {
        fontSize: 14,
        color: "#666",
    },
    removeUser: {
        fontSize: 18,
        color: "red",
        fontWeight: "bold",
        marginLeft: 10,
    },
    dateInput: {
        height: 40,
        justifyContent: "center",
        alignItems: "center",
        borderColor: "#ccc",
        borderWidth: 1,
        borderRadius: 8,
        paddingHorizontal: 10,
        marginBottom: 15,
        textAlign: "center",
        backgroundColor: "#f9f9f9",
        color: "#333",
    },
});
