spring:
  datasource:
    url: jdbc:mysql://switchyard.proxy.rlwy.net:44940/railway
    username: root
    password: kEuDFxffYxlcmnelTtvEXdimhgbANZoJ
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
