spring:
  datasource:
    url: jdbc:mysql://localhost:3306/taskflowdb
    username: root
    password: 12345678
  jpa:
    database-platform: org.hibernate.dialect.MySQLDialect
    hibernate:
      ddl-auto: update
    show-sql: true
    open-in-view: false
